title: "Tony O’Halloran"
description: "AI Researcher | MSc Thesis, Yale/EPFL LiGHT"
theme: minima
url: "https://tonyohalloran.github.io"
author:
  name: "Tony O'Halloran"
  email: "your-email@example.com"

minima:
  skin: dark
