title: "Tony O’Halloran"
description: "AI Researcher | MSc Thesis, Yale/EPFL LiGHT | Healthcare & Mechanistic Interpretability"
theme: minima
url: "https://tonyohalloran.github.io"
author: 
  name: "Tony O'Halloran"
  email: "tonyohalloran2000@gmail.com"
